version: '3.3'

services:
   mongodb:
      image: "mongo:latest"
      restart: always
      command: --nojournal
      volumes:
         - type: volume
           source: db
           target: /data/db

   girder:
      image: fepegar/dsa_minimal  # https://docs.microsoft.com/en-us/azure/app-service/configure-custom-container?pivots=container-linux#configure-multi-container-apps
      restart: always
      ports:
         - "443:8080"  # 443 is the HTTPS port. 8080 is the default DSA port
      volumes:
         - type: volume
           source: assetstore
           target: /assetstore
         - type: bind
           source: ${WEBAPP_STORAGE_HOME}/iedatasets
           target: /iedatasets
         - type: bind
           source: /tmp/datasets
           target: /datasets
      depends_on:
         - mongodb
volumes:
   assetstore:
   db:
