version: '3.3'

services:
   mongodb:
      image: "mongo:latest"
      restart: always
      command: --nojournal
      volumes:
         - db:/data/db

   girder:
      image: fepegar/dsa_minimal  # https://docs.microsoft.com/en-us/azure/app-service/configure-custom-container?pivots=container-linux#configure-multi-container-apps
      restart: always
      ports:
         - "443:8080"  # 443 is the HTTPS port. 8080 is the default DSA port
      volumes:
         - assetstore:/assetstore
         - ${WEBAPP_STORAGE_HOME}/iedatasets:/iedatasets
      depends_on:
         - mongodb
volumes:
   assetstore:
   db:
