version: '3.3'

services:
   mongodb:
      image: "mongo:latest"
      restart: always
      command: --nojournal
      volumes:
         - db:/data/db

   girder:
      image: fepegar/dsa_minimal  # building the image doesn't seem to be allowed on Azure
      restart: always
      ports:
         - "443:8080"  # 443 is the HTTPS port. 8080 is the default DSA port
      volumes:
         - assetstore:/assetstore
      depends_on:
         - mongodb
volumes:
   assetstore:
   db:
